### PR TITLE
Add dnslib to requirements

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by 0xInfection** [comment]
Is `dnslib` actually required somewhere? As far as my knowledge goes, it isn't a dependency. Are you getting a `ModuleNotFound` error somewhere? If yes please let me know!

**Comment by ChillerDragon** [comment]
Sure i wasn't able to run tidos because of module not found until i did ``pip2 install dnslib``

**Comment by 0xInfection** [comment]
Can you show me a screenshot? Or maybe paste the output here? Cause I cannot reproduce this. I don't have dnslib installed, yet TIDoS runs fine.

**Comment by ChillerDragon** [comment]
Ubuntu 18.04.2 LTS x86_64
```
$ sudo ./tidos.py 
[sudo] password for chiller: 
Traceback (most recent call last):
  File "./tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/home/chiller/Desktop/git-extern/TIDoS-Framework/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/home/chiller/Desktop/git-extern/TIDoS-Framework/core/Vulnlysis/vuln.py", line 16, in <module>
    from core.Vulnlysis.Misc_Bugs.webbugs import *
  File "/home/chiller/Desktop/git-extern/TIDoS-Framework/core/Vulnlysis/Misc_Bugs/webbugs.py", line 29, in <module>
    from mailspoof import *
  File "modules/0x03-Vulnerability+Analysis/0x02-MisconfigurationBugs/mailspoof.py", line 15, in <module>
    import emailprotectionslib.dmarc as dmarclib
  File "/home/chiller/.local/lib/python2.7/site-packages/emailprotectionslib/dmarc.py", line 3, in <module>
    import Resolver
  File "/home/chiller/.local/lib/python2.7/site-packages/emailprotectionslib/Resolver.py", line 1, in <module>
    import dnslib
ImportError: No module named dnslib
```

**Comment by 0xInfection** [comment]
Hmm somehow it isn't a dependency in Kali. Thank you!

**Pull request merged**
